//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalTeleinf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITA_TIPOEXAMEN
    {
        public int ID_CITA_EXAMEN { get; set; }
        public Nullable<int> ID_TIPOEXAMEN { get; set; }
        public Nullable<int> ID_NOMBRE_EXAMEN { get; set; }
        public Nullable<int> ID_CITA { get; set; }
    
        public virtual CITA CITA { get; set; }
        public virtual TIPOEXAMEN TIPOEXAMEN { get; set; }
        public virtual NOMBRE_EXAMEN NOMBRE_EXAMEN { get; set; }
    }
}
