//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalTeleinf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO_EXAMEN
    {
        public int ID_RESULTADOEXAMEN { get; set; }
        public Nullable<int> ID_NOMBRE_EXAMEN { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<int> ID_TIPOEXAMEN { get; set; }
        public Nullable<int> ID_RESULTADOPACIENTE { get; set; }
    
        public virtual NOMBRE_EXAMEN NOMBRE_EXAMEN { get; set; }
        public virtual RESULTADO_PACIENTE RESULTADO_PACIENTE { get; set; }
        public virtual TIPOEXAMEN TIPOEXAMEN { get; set; }
    }
}
