//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalTeleinf.Models.ViewModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laboratorioDBEntities2 : DbContext
    {
        public laboratorioDBEntities2()
            : base("name=laboratorioDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CITA> CITA { get; set; }
        public virtual DbSet<CITA_TIPOEXAMEN> CITA_TIPOEXAMEN { get; set; }
        public virtual DbSet<NOMBRE_EXAMEN> NOMBRE_EXAMEN { get; set; }
        public virtual DbSet<RESULTADO_EXAMEN> RESULTADO_EXAMEN { get; set; }
        public virtual DbSet<RESULTADO_PACIENTE> RESULTADO_PACIENTE { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPOEXAMEN> TIPOEXAMEN { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
