//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinalTeleinf.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO_EXAMEN
    {
        public int ID_RESULTADOEXAMEN { get; set; }
        public Nullable<int> ID_NOMBRE_EXAMEN { get; set; }
        public string RESULTADO { get; set; }
        public Nullable<int> ID_TIPOEXAMEN { get; set; }
        public Nullable<int> ID_RESULTADOPACIENTE { get; set; }
    
        public virtual NOMBRE_EXAMEN NOMBRE_EXAMEN { get; set; }
        public virtual RESULTADO_PACIENTE RESULTADO_PACIENTE { get; set; }
        public virtual TIPOEXAMEN TIPOEXAMEN { get; set; }
    }
}
